Day 7/MVC Structure/Demo1/Models/Department.cs
namespace Demo1.Models
{
    public class Department
    {
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
    }
}

Day 7/MVC Structure/Demo1/Models/ErrorViewModel.cs
namespace Demo1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day 7/MVC Structure/Demo1/Controllers/DepatmentsController.cs
using Demo1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Demo1.Controllers
{
    public class DepatmentsController : Controller
    {
        static List<Department> departments = new List<Department>
        {
            new Department() { DepartmentId = 1, Name = "HR", Location = "Delhi" },
            new Department() { DepartmentId = 2, Name = "IT", Location = "Indore" },
            new Department() { DepartmentId = 3, Name = "Admin", Location = "Bhopal" },
            new Department() { DepartmentId = 4, Name = "Transport", Location = "Pune" },
        };

        public DepatmentsController() { }

        // GET: /Depatments/
        public IActionResult Index()
        {
            return View(departments);
        }

        // GET: /Depatments/Details/5
        public IActionResult Details(int id)
        {
            var department = departments.FirstOrDefault(x => x.DepartmentId == id);
            if (department != null)
            {
                return View(department);
            }
            return RedirectToAction("Index");
        }

        // GET: /Depatments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: /Depatments/Create
        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                departments.Add(department);
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: /Depatments/Edit/5
        public IActionResult Edit(int id)
        {
            var department = departments.FirstOrDefault(x => x.DepartmentId == id);
            if (department != null)
            {
                return View(department);
            }
            return RedirectToAction("Index");
        }

        // POST: /Depatments/Edit/5
        [HttpPost]
        public IActionResult Edit(Department updateDepartment)
        {
            if (ModelState.IsValid)
            {
                var department = departments.FirstOrDefault(x => x.DepartmentId == updateDepartment.DepartmentId);
                if (department != null)
                {
                    department.Name = updateDepartment.Name;
                    department.Location = updateDepartment.Location;
                    return RedirectToAction("Index");
                }
            }
            return View(updateDepartment);
        }

        // GET: /Depatments/Delete/5
        public IActionResult Delete(int id)
        {
            var department = departments.FirstOrDefault(x => x.DepartmentId == id);
            if (department != null)
            {
                return View(department);
            }
            return RedirectToAction("Index");
        }

        // POST: /Depatments/DeleteConfirmed
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            var department = departments.FirstOrDefault(x => x.DepartmentId == id);
            if (department != null)
            {
                departments.Remove(department);
            }
            return RedirectToAction("Index");
        }
    }
}

Day 7/MVC Structure/Demo1/Controllers/HomeController.cs
using Demo1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Demo1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day 7/MVC Structure/Demo1/Views/Depatments/Create.cshtml
@model Demo1.Models.Department

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <input asp-for="DepartmentId" class="form-control" />
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Day 7/MVC Structure/Demo1/Views/Depatments/Delete.cshtml
@model Demo1.Models.Department

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed" method="post">
        <!-- Hidden field to pass the DepartmentId -->
        <input type="hidden" asp-for="DepartmentId" />

        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Day 7/MVC Structure/Demo1/Views/Depatments/Details.cshtml
@model Demo1.Models.Department;

<h1>Departments Details Page</h1>

<h3>DepartmentId : @Model.DepartmentId</h3>
<h3>Name: @Model.Name</h3>
<h3>Loation : @Model.Location</h3>

 

Day 7/MVC Structure/Demo1/Views/Depatments/Edit.cshtml
@model Demo1.Models.Department

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <input asp-for="DepartmentId" class="form-control" />
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Day 7/MVC Structure/Demo1/Views/Depatments/Index.cshtml
@model IEnumerable<Demo1.Models.Department>

<h1>This is the Departments Controller Index Page</h1>

<h3>@ViewData["Message"]</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Location</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.DepartmentId</td>
                <td>@item.Name</td>
                <td>@item.Location</td>
                <td>
                    <a asp-controller="Depatments" asp-action="Details" asp-route-id="@item.DepartmentId">Detail</a> |
                    <a asp-controller="Depatments" asp-action="Edit" asp-route-id="@item.DepartmentId">Edit</a> |
                    <a asp-controller="Depatments" asp-action="Delete" asp-route-id="@item.DepartmentId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@* Example of a commented-out section (not displayed in the view) *@

Day 7/MVC Structure/Demo1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Day 7/MVC Structure/Demo1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Depatments" asp-action="Index">Department Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Depatments" asp-action="Details">Department Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>